import { Theme } from "../types/types";

export const dummyThemes: Theme[] = [
  {
    id: "modern-dark",
    name: "Modern Dark",
    backgroundPrimary: { hue: 220, saturation: 15, lightness: 15 },
    backgroundSecondary: { hue: 220, saturation: 15, lightness: 20 },
    textPrimary: { hue: 0, saturation: 0, lightness: 90 },
    textSecondary: { hue: 0, saturation: 0, lightness: 70 },
  },
  {
    id: "light-mode",
    name: "Light Mode",
    backgroundPrimary: { hue: 0, saturation: 0, lightness: 100 },
    backgroundSecondary: { hue: 0, saturation: 0, lightness: 95 },
    textPrimary: { hue: 220, saturation: 15, lightness: 20 },
    textSecondary: { hue: 220, saturation: 10, lightness: 40 },
  },
  {
    id: "forest",
    name: "Forest",
    backgroundPrimary: { hue: 150, saturation: 30, lightness: 15 },
    backgroundSecondary: { hue: 150, saturation: 25, lightness: 20 },
    textPrimary: { hue: 80, saturation: 80, lightness: 85 },
    textSecondary: { hue: 80, saturation: 60, lightness: 70 },
  },
  {
    id: "ocean",
    name: "Ocean",
    backgroundPrimary: { hue: 200, saturation: 70, lightness: 20 },
    backgroundSecondary: { hue: 200, saturation: 60, lightness: 25 },
    textPrimary: { hue: 180, saturation: 50, lightness: 90 },
    textSecondary: { hue: 180, saturation: 40, lightness: 75 },
  },
  {
    id: "sunset",
    name: "Sunset",
    backgroundPrimary: { hue: 20, saturation: 60, lightness: 20 },
    backgroundSecondary: { hue: 20, saturation: 50, lightness: 25 },
    textPrimary: { hue: 40, saturation: 100, lightness: 85 },
    textSecondary: { hue: 40, saturation: 80, lightness: 70 },
  },
  {
    id: "lavender",
    name: "Lavender",
    backgroundPrimary: { hue: 270, saturation: 25, lightness: 25 },
    backgroundSecondary: { hue: 270, saturation: 20, lightness: 30 },
    textPrimary: { hue: 290, saturation: 40, lightness: 90 },
    textSecondary: { hue: 290, saturation: 30, lightness: 75 },
  },
  {
    id: "mint",
    name: "Mint",
    backgroundPrimary: { hue: 160, saturation: 40, lightness: 20 },
    backgroundSecondary: { hue: 160, saturation: 35, lightness: 25 },
    textPrimary: { hue: 140, saturation: 60, lightness: 85 },
    textSecondary: { hue: 140, saturation: 50, lightness: 70 },
  },
  {
    id: "rose",
    name: "Rose",
    backgroundPrimary: { hue: 340, saturation: 30, lightness: 20 },
    backgroundSecondary: { hue: 340, saturation: 25, lightness: 25 },
    textPrimary: { hue: 350, saturation: 70, lightness: 90 },
    textSecondary: { hue: 350, saturation: 60, lightness: 75 },
  },
  {
    id: "coffee",
    name: "Coffee",
    backgroundPrimary: { hue: 30, saturation: 40, lightness: 15 },
    backgroundSecondary: { hue: 30, saturation: 35, lightness: 20 },
    textPrimary: { hue: 40, saturation: 50, lightness: 85 },
    textSecondary: { hue: 40, saturation: 40, lightness: 70 },
  },
  {
    id: "arctic",
    name: "Arctic",
    backgroundPrimary: { hue: 200, saturation: 15, lightness: 95 },
    backgroundSecondary: { hue: 200, saturation: 20, lightness: 90 },
    textPrimary: { hue: 210, saturation: 70, lightness: 20 },
    textSecondary: { hue: 210, saturation: 60, lightness: 35 },
  },
];
