import { Task } from "@/types/types";

export const dummyTasks: Task[] = [
  {
    id: "task-1",
    title: "Design User Interface",
    description: "Create wireframes and mockups for the new dashboard",
    status: "notStarted",
    epicId: "epic-2",
  },
  {
    id: "task-2",
    title: "Implement Authentication",
    description: "Set up user authentication using NextAuth.js",
    status: "inProgress",
    epicId: "epic-1",
  },
  {
    id: "task-3",
    title: "Write API Documentation",
    description: "Document all API endpoints and their usage",
    status: "completed",
    epicId: "epic-3",
  },
  {
    id: "task-4",
    title: "Fix Navigation Bug",
    description: "Debug and fix the navigation menu responsiveness issue",
    status: "archived",
    epicId: "epic-2",
  },
  {
    id: "task-5",
    title: "Database Schema Design",
    description: "Design and document the database schema for user management",
    status: "notStarted",
    epicId: "epic-5",
  },
  {
    id: "task-6",
    title: "Optimize Image Loading",
    description: "Implement lazy loading for images to improve performance",
    status: "inProgress",
    epicId: "epic-2",
  },
  {
    id: "task-7",
    title: "Unit Test Components",
    description: "Write comprehensive unit tests for React components",
    status: "notStarted",
    epicId: "epic-3",
  },
  {
    id: "task-8",
    title: "Setup CI/CD Pipeline",
    description: "Configure GitHub Actions for automated deployment",
    status: "completed",
    epicId: "epic-5",
  },
  {
    id: "task-9",
    title: "Implement Search Feature",
    description: "Add full-text search functionality to the dashboard",
    status: "inProgress",
    epicId: "epic-1",
  },
  {
    id: "task-10",
    title: "Mobile Responsiveness",
    description: "Ensure all pages are properly responsive on mobile devices",
    status: "notStarted",
    epicId: "epic-1",
  },
  {
    id: "task-11",
    title: "Error Handling",
    description: "Implement global error boundary and error pages",
    status: "archived",
    epicId: "epic-5",
  },
  {
    id: "task-12",
    title: "Performance Monitoring",
    description: "Set up performance monitoring tools and analytics",
    status: "notStarted",
    epicId: "epic-2",
  },
  {
    id: "task-13",
    title: "Security Audit",
    description: "Conduct security assessment and fix vulnerabilities",
    status: "inProgress",
    epicId: "epic-1",
  },
  {
    id: "task-14",
    title: "Accessibility Review",
    description: "Ensure WCAG 2.1 compliance across all features",
    status: "notStarted",
    epicId: "epic-1",
  },
  {
    id: "task-15",
    title: "Data Export Feature",
    description: "Add functionality to export data in CSV/PDF formats",
    status: "completed",
    epicId: "epic-3",
  },
  {
    id: "task-16",
    title: "User Onboarding Flow",
    description: "Design and implement user onboarding experience",
    status: "inProgress",
    epicId: "epic-1",
  },
  {
    id: "task-17",
    title: "API Rate Limiting",
    description: "Implement rate limiting for API endpoints",
    status: "notStarted",
    epicId: "epic-1",
  },
  {
    id: "task-18",
    title: "Password Reset Flow",
    description: "Add forgot password and reset functionality",
    status: "completed",
    epicId: "epic-1",
  },
  {
    id: "task-19",
    title: "Code Documentation",
    description: "Update inline code documentation and README files",
    status: "archived",
    epicId: "epic-3",
  },
  {
    id: "task-20",
    title: "Third-party Integrations",
    description: "Integrate with external payment and analytics services",
    status: "notStarted",
    epicId: "epic-5",
  },
];
