import { Task } from "@/types/types";

export const dummyTasks: Task[] = [
  {
    id: "task-1",
    title: "Design User Interface",
    description: "Create wireframes and mockups for the new dashboard",
    status: "notStarted",
    ticketType: "task",
    epicId: "epic-2",
    dueDate: new Date("2024-04-15"),
  },
  {
    id: "task-2",
    title: "Implement Authentication",
    description: "Set up user authentication using NextAuth.js",
    status: "inProgress",
    ticketType: "task",
    epicId: "epic-1",
    dueDate: new Date("2024-05-10"),
  },
  {
    id: "task-3",
    title: "Write API Documentation",
    description: "Document all API endpoints and their usage",
    status: "completed",
    ticketType: "task",
    epicId: "epic-3",
    dueDate: new Date("2024-06-15"),
  },
  {
    id: "task-4",
    title: "Fix Navigation Bug",
    description: "Debug and fix the navigation menu responsiveness issue",
    status: "archived",
    ticketType: "task",
    epicId: "epic-2",
    dueDate: new Date("2024-07-20"),
  },
  {
    id: "task-5",
    title: "Database Schema Design",
    description: "Design and document the database schema for user management",
    status: "notStarted",
    ticketType: "task",
    epicId: "epic-5",
    dueDate: new Date("2024-08-25"),
  },
  {
    id: "task-6",
    title: "Optimize Image Loading",
    description: "Implement lazy loading for images to improve performance",
    status: "inProgress",
    ticketType: "task",
    epicId: "epic-2",
    dueDate: new Date("2024-09-30"),
  },
  {
    id: "task-7",
    title: "Unit Test Components",
    description: "Write comprehensive unit tests for React components",
    status: "notStarted",
    ticketType: "task",
    epicId: "epic-3",
    dueDate: new Date("2024-10-31"),
  },
  {
    id: "task-8",
    title: "Setup CI/CD Pipeline",
    description: "Configure GitHub Actions for automated deployment",
    status: "completed",
    ticketType: "task",
    epicId: "epic-5",
    dueDate: new Date("2024-11-15"),
  },
  {
    id: "task-9",
    title: "Implement Search Feature",
    description: "Add full-text search functionality to the dashboard",
    status: "inProgress",
    ticketType: "task",
    epicId: "epic-1",
    dueDate: new Date("2024-12-20"),
  },
  {
    id: "task-10",
    title: "Mobile Responsiveness",
    description: "Ensure all pages are properly responsive on mobile devices",
    status: "notStarted",
    ticketType: "task",
    epicId: "epic-1",
    dueDate: new Date("2025-01-25"),
  },
  {
    id: "task-11",
    title: "Error Handling",
    description: "Implement global error boundary and error pages",
    status: "archived",
    ticketType: "task",
    epicId: "epic-5",
    dueDate: new Date("2025-02-28"),
  },
  {
    id: "task-12",
    title: "Performance Monitoring",
    description: "Set up performance monitoring tools and analytics",
    status: "notStarted",
    ticketType: "task",
    epicId: "epic-2",
    dueDate: new Date("2025-03-31"),
  },
  {
    id: "task-13",
    title: "Security Audit",
    description: "Conduct security assessment and fix vulnerabilities",
    status: "inProgress",
    ticketType: "task",
    epicId: "epic-1",
    dueDate: new Date("2025-04-15"),
  },
  {
    id: "task-14",
    title: "Accessibility Review",
    description: "Ensure WCAG 2.1 compliance across all features",
    status: "notStarted",
    ticketType: "task",
    epicId: "epic-1",
    dueDate: new Date("2025-05-20"),
  },
  {
    id: "task-15",
    title: "Data Export Feature",
    description: "Add functionality to export data in CSV/PDF formats",
    status: "completed",
    ticketType: "task",
    epicId: "epic-3",
    dueDate: new Date("2025-06-25"),
  },
  {
    id: "task-16",
    title: "User Onboarding Flow",
    description: "Design and implement user onboarding experience",
    status: "inProgress",
    ticketType: "task",
    epicId: "epic-1",
    dueDate: new Date("2025-07-30"),
  },
  {
    id: "task-17",
    title: "API Rate Limiting",
    description: "Implement rate limiting for API endpoints",
    status: "notStarted",
    ticketType: "task",
    epicId: "epic-1",
    dueDate: new Date("2025-08-31"),
  },
  {
    id: "task-18",
    title: "Password Reset Flow",
    description: "Add forgot password and reset functionality",
    status: "completed",
    ticketType: "task",
    epicId: "epic-1",
    dueDate: new Date("2025-09-15"),
  },
  {
    id: "task-19",
    title: "Code Documentation",
    description: "Update inline code documentation and README files",
    status: "archived",
    ticketType: "task",
    epicId: "epic-3",
    dueDate: new Date("2025-10-20"),
  },
  {
    id: "task-20",
    title: "Third-party Integrations",
    description: "Integrate with external payment and analytics services",
    status: "notStarted",
    ticketType: "task",
    epicId: "epic-5",
    dueDate: new Date("2025-11-25"),
  },
  {
    id: "task-21",
    title: "Email Notification System",
    description: "Implement automated email notifications for user actions",
    status: "inProgress",
    ticketType: "task",
    epicId: "epic-2",
    dueDate: new Date("2025-12-30"),
  },
  {
    id: "task-22",
    title: "Dark Mode Implementation",
    description: "Add dark mode theme support across the application",
    status: "notStarted",
    ticketType: "task",
    epicId: "epic-2",
    dueDate: new Date("2026-01-31"),
  },
  {
    id: "task-23",
    title: "User Activity Logging",
    description: "Create logging system for user actions and events",
    status: "completed",
    ticketType: "task",
    epicId: "epic-5",
    dueDate: new Date("2026-02-28"),
  },
  {
    id: "task-24",
    title: "Cache Implementation",
    description: "Set up Redis caching for frequently accessed data",
    status: "inProgress",
    ticketType: "task",
    epicId: "epic-3",
    dueDate: new Date("2026-03-31"),
  },
  {
    id: "task-25",
    title: "Bulk Data Import",
    description: "Add functionality to import data in bulk via CSV",
    status: "notStarted",
    ticketType: "task",
    epicId: "epic-5",
    dueDate: new Date("2026-04-30"),
  },
  {
    id: "task-26",
    title: "API Version Control",
    description: "Implement API versioning system for backward compatibility",
    status: "archived",
    ticketType: "task",
    epicId: "epic-3",
    dueDate: new Date("2026-05-31"),
  },
  {
    id: "task-27",
    title: "Dashboard Analytics",
    description: "Create analytics dashboard with key metrics visualization",
    status: "inProgress",
    ticketType: "task",
    epicId: "epic-2",
    dueDate: new Date("2026-06-30"),
  },
  {
    id: "task-28",
    title: "Multi-language Support",
    description: "Implement i18n for multiple language support",
    status: "notStarted",
    ticketType: "task",
    epicId: "epic-1",
    dueDate: new Date("2026-07-31"),
  },
  {
    id: "task-29",
    title: "Backup System",
    description: "Set up automated database backup and recovery system",
    status: "completed",
    ticketType: "task",
    epicId: "epic-5",
    dueDate: new Date("2026-08-31"),
  },
  {
    id: "task-30",
    title: "API Health Monitoring",
    description: "Implement health checks and monitoring for API endpoints",
    status: "inProgress",
    ticketType: "task",
    epicId: "epic-3",
    dueDate: new Date("2026-09-30"),
  },
  {
    id: "task-31",
    title: "User Feedback System",
    description: "Create in-app feedback collection mechanism",
    status: "notStarted",
    ticketType: "task",
    epicId: "epic-1",
    dueDate: new Date("2026-10-31"),
  },
  {
    id: "task-32",
    title: "File Upload System",
    description: "Implement secure file upload with validation",
    status: "completed",
    ticketType: "task",
    epicId: "epic-2",
    dueDate: new Date("2026-11-30"),
  },
  {
    id: "task-33",
    title: "Session Management",
    description: "Enhance user session handling and timeout features",
    status: "inProgress",
    ticketType: "task",
    epicId: "epic-1",
    dueDate: new Date("2026-12-31"),
  },
  {
    id: "task-34",
    title: "API Documentation UI",
    description: "Create interactive API documentation using Swagger",
    status: "archived",
    ticketType: "task",
    epicId: "epic-3",
    dueDate: new Date("2027-01-31"),
  },
  {
    id: "task-35",
    title: "Performance Optimization",
    description: "Optimize database queries and API response times",
    status: "notStarted",
    ticketType: "task",
    epicId: "epic-5",
    dueDate: new Date("2027-02-28"),
  },
  {
    id: "task-36",
    title: "User Role Management",
    description: "Implement role-based access control system",
    status: "inProgress",
    ticketType: "task",
    epicId: "epic-1",
    dueDate: new Date("2027-03-31"),
  },
  {
    id: "task-37",
    title: "Audit Trail System",
    description: "Create audit logs for critical system operations",
    status: "completed",
    ticketType: "task",
    epicId: "epic-5",
    dueDate: new Date("2027-04-30"),
  },
  {
    id: "task-38",
    title: "Data Validation Layer",
    description: "Implement comprehensive input validation system",
    status: "notStarted",
    ticketType: "task",
    epicId: "epic-3",
    dueDate: new Date("2027-05-31"),
  },
  {
    id: "task-39",
    title: "Real-time Updates",
    description: "Add WebSocket support for real-time data updates",
    status: "inProgress",
    ticketType: "task",
    epicId: "epic-2",
    dueDate: new Date("2027-06-30"),
  },
  {
    id: "task-40",
    title: "SSO Integration",
    description: "Implement Single Sign-On with major providers",
    status: "notStarted",
    ticketType: "task",
    epicId: "epic-1",
    dueDate: new Date("2027-07-31"),
  },
];
